5to_HospeddApp_C#/Hotel.Mvc/Controllers/Hotel_CuartoController.cs
using HotelApp.Core;
using Microsoft.AspNetCore.Mvc;

namespace HotelApp.Mvc.Controllers
{
    public class Hotel_CuartoController : Controller
    {
        private readonly IAdo _Hotel_Cuarto;
        public Hotel_CuartoController(IAdo ado) => _Hotel_Cuarto = ado;

        [HttpGet]
        public async Task<IActionResult> Busqueda()
        {
            var Busqueda = await _Hotel_Cuarto.ObtenerCuartoAsync();
            return View(Busqueda);
        }

        [HttpGet]
        public async Task<IActionResult> Buscar(string? busqueda)
        {
            if (busqueda == null)
                return View("Busqueda", await _Hotel_Cuarto.ObtenerHotel_CuartoAsync());
            IEnumerable<Hotel_Cuarto>? hotel_cuarto = null;
            if (!string.IsNullOrEmpty(busqueda))
            {
                hotel_cuarto = await _Hotel_Cuarto.BuscarHotel_CuartoAsync(busqueda);
                if (hotel_cuarto.Count() == 0)
                    return View("NoEncontrado");
            }
            hotel_cuarto = hotel_cuarto ?? new List<Hotel_Cuarto>();
            return View("Busqueda", hotel_cuarto);
        }

        [HttpGet]
        public IActionResult Alta() => View("Upsert");

        [HttpGet]
        public async Task<IActionResult> Modificar(ushort? IdHotel, byte? IdCuarto)
        {
            if (IdHotel is null || IdHotel == 0)
                return NotFound();

            var existe = await _Hotel_Cuarto.ObtenerHotel_CuartoPorIdAsync(IdHotel, IdCuarto);
            if (existe is null)
                return NotFound();

            return View("Upsert", existe);
        }

        [HttpPost]
        public async Task<IActionResult> Upsert(Hotel_Cuarto hotel_Cuarto)
        {
            try
            {
                if (hotel_Cuarto.Numero == 0 || hotel_Cuarto.Numero == null)
                    await _Hotel_Cuarto.AltaHotel_CuartoAsync(hotel_Cuarto);
                else
                {
                    var existe = await _Hotel_Cuarto.ObtenerHotel_CuartoPorIdAsync(hotel_Cuarto.IdHotel, hotel_Cuarto.IdCuarto);
                    if (existe is null)
                        return NotFound();

                    await _Hotel_Cuarto.ModificarHotel_Cuarto(hotel_Cuarto);
                }
            }
            catch
            {
                return NotFound();
            }
            return RedirectToAction("Busqueda");
        }
    }
}

5to_HospeddApp_C#/Hotel.Mvc/Views/Cliente/Listado.cshtml
@using HotelApp.Core;
@model IEnumerable<Cliente>;
@{
        ViewData["Title"] = "Clientes";
}

<div class="text-center">
    <h1>Buscar</h1>
</div>
<div class="text-center">

    <form asp-controller="Cliente" asp-action="Buscar" method="get">
        <input type="text" name="Busqueda" />
        <input type="submit" value="Buscar" />
    </form>
</div>


@if (Model.Count() == 0 && Context.Request.RouteValues.ContainsKey("Busqueda"))
    {
        <p>No se encontraron personas.</p>
    }
    else
    {
        <br><br>
        <table class="table table-striped">
                <thead>
                <tr>
                        <th scope="col">Dni</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Apellido</th>
                        <th scope="col">Email</th>
                </tr>
                </thead>
                <tbody class="">
                @foreach (var cliente in Model)
                {
                        <tr>
                        <th scope="row">@cliente.Dni</th>
                        <td>@cliente.Nombre</td>
                        <td>@cliente.Apellido</td>
                        <td>@cliente.Email</td>
                        </tr>
                }
                </tbody>
        </table>
}

5to_HospeddApp_C#/Hotel.Mvc/Views/Hotel_Cuarto/Upsert.cshtml
@using HotelApp.Core;
@model Hotel_Cuarto;
@{
    var texto = Model is null ? "Alta Hotel_Cuarto" : "Modificar Hotel_Cuarto";
    ViewData["Title"] = texto;
}

<form asp-controller="Hotel_Cuarto" asp-action="Upsert" method="post">
    <div asp-validation-summary="All"></div>
    @if (Model != null)
    {
        <div><input type="hidden" asp-for="@Model.Numero" /></div>
    }
    <div class="mb-3">
        <label asp-for="IdHotel" class="form-label">Id del Hotel</label>
        <input asp-for="IdHotel" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="IdCuarto" class="form-label">Id del Cuarto</label>
        <input asp-for="IdCuarto" class="form-control" />
    </div>
    <div class="mb-3">
        @if (Model is null)
        {
            <button type="submit" class="btn btn-primary">@texto</button>
        }
        else
        {
            <button type="submit" class="btn btn-warning">@texto</button>
        }
    </div>
</form>